//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名:
// 生成日期: 2009-09-16 22:12:35
namespace AzureCalendarMvcWeb.Models
{
    
    /// <summary>
    /// 架构中不存在 AzureCalendarDb 的注释。
    /// </summary>
    public partial class AzureCalendarDb : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“AzureCalendarDb”部分中的连接字符串初始化新 AzureCalendarDb 对象。
        /// </summary>
        public AzureCalendarDb() : 
                base("name=AzureCalendarDb", "AzureCalendarDb")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 AzureCalendarDb 对象。
        /// </summary>
        public AzureCalendarDb(string connectionString) : 
                base(connectionString, "AzureCalendarDb")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 AzureCalendarDb 对象。
        /// </summary>
        public AzureCalendarDb(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "AzureCalendarDb")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Calendars 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Calendar> Calendars
        {
            get
            {
                if ((this._Calendars == null))
                {
                    this._Calendars = base.CreateQuery<Calendar>("[Calendars]");
                }
                return this._Calendars;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Calendar> _Calendars;
        /// <summary>
        /// 架构中不存在 UserInfo 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UserInfo> UserInfo
        {
            get
            {
                if ((this._UserInfo == null))
                {
                    this._UserInfo = base.CreateQuery<UserInfo>("[UserInfo]");
                }
                return this._UserInfo;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UserInfo> _UserInfo;
        /// <summary>
        /// 架构中不存在 Calendars 的注释。
        /// </summary>
        public void AddToCalendars(Calendar calendar)
        {
            base.AddObject("Calendars", calendar);
        }
        /// <summary>
        /// 架构中不存在 UserInfo 的注释。
        /// </summary>
        public void AddToUserInfo(UserInfo userInfo)
        {
            base.AddObject("UserInfo", userInfo);
        }
    }
    /// <summary>
    /// 架构中不存在 AzureCalEntities.Calendar 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AzureCalEntities", Name="Calendar")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Calendar : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Calendar 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="calendarType">CalendarType 的初始值。</param>
        /// <param name="startTime">StartTime 的初始值。</param>
        /// <param name="endTime">EndTime 的初始值。</param>
        /// <param name="hasAttachment">HasAttachment 的初始值。</param>
        /// <param name="instanceType">InstanceType 的初始值。</param>
        /// <param name="uPAccount">UPAccount 的初始值。</param>
        /// <param name="uPName">UPName 的初始值。</param>
        /// <param name="uPTime">UPTime 的初始值。</param>
        /// <param name="isAllDayEvent">IsAllDayEvent 的初始值。</param>
        public static Calendar CreateCalendar(int id, int calendarType, global::System.DateTime startTime, global::System.DateTime endTime, bool hasAttachment, int instanceType, string uPAccount, string uPName, global::System.DateTime uPTime, bool isAllDayEvent)
        {
            Calendar calendar = new Calendar();
            calendar.Id = id;
            calendar.CalendarType = calendarType;
            calendar.StartTime = startTime;
            calendar.EndTime = endTime;
            calendar.HasAttachment = hasAttachment;
            calendar.InstanceType = instanceType;
            calendar.UPAccount = uPAccount;
            calendar.UPName = uPName;
            calendar.UPTime = uPTime;
            calendar.IsAllDayEvent = isAllDayEvent;
            return calendar;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Subject 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this.ReportPropertyChanging("Subject");
                this._Subject = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subject");
                this.OnSubjectChanged();
            }
        }
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// 架构中不存在属性 Location 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this.ReportPropertyChanging("Location");
                this._Location = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Location");
                this.OnLocationChanged();
            }
        }
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// 架构中不存在属性 MasterId 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MasterId
        {
            get
            {
                return this._MasterId;
            }
            set
            {
                this.OnMasterIdChanging(value);
                this.ReportPropertyChanging("MasterId");
                this._MasterId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MasterId");
                this.OnMasterIdChanged();
            }
        }
        private global::System.Nullable<int> _MasterId;
        partial void OnMasterIdChanging(global::System.Nullable<int> value);
        partial void OnMasterIdChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 CalendarType 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CalendarType
        {
            get
            {
                return this._CalendarType;
            }
            set
            {
                this.OnCalendarTypeChanging(value);
                this.ReportPropertyChanging("CalendarType");
                this._CalendarType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CalendarType");
                this.OnCalendarTypeChanged();
            }
        }
        private int _CalendarType;
        partial void OnCalendarTypeChanging(int value);
        partial void OnCalendarTypeChanged();
        /// <summary>
        /// 架构中不存在属性 StartTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                this.ReportPropertyChanging("StartTime");
                this._StartTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartTime");
                this.OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// 架构中不存在属性 EndTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return this._EndTime;
            }
            set
            {
                this.OnEndTimeChanging(value);
                this.ReportPropertyChanging("EndTime");
                this._EndTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndTime");
                this.OnEndTimeChanged();
            }
        }
        private global::System.DateTime _EndTime;
        partial void OnEndTimeChanging(global::System.DateTime value);
        partial void OnEndTimeChanged();
        /// <summary>
        /// 架构中不存在属性 HasAttachment 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAttachment
        {
            get
            {
                return this._HasAttachment;
            }
            set
            {
                this.OnHasAttachmentChanging(value);
                this.ReportPropertyChanging("HasAttachment");
                this._HasAttachment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HasAttachment");
                this.OnHasAttachmentChanged();
            }
        }
        private bool _HasAttachment;
        partial void OnHasAttachmentChanging(bool value);
        partial void OnHasAttachmentChanged();
        /// <summary>
        /// 架构中不存在属性 Category 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this.ReportPropertyChanging("Category");
                this._Category = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Category");
                this.OnCategoryChanged();
            }
        }
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// 架构中不存在属性 InstanceType 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int InstanceType
        {
            get
            {
                return this._InstanceType;
            }
            set
            {
                this.OnInstanceTypeChanging(value);
                this.ReportPropertyChanging("InstanceType");
                this._InstanceType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("InstanceType");
                this.OnInstanceTypeChanged();
            }
        }
        private int _InstanceType;
        partial void OnInstanceTypeChanging(int value);
        partial void OnInstanceTypeChanged();
        /// <summary>
        /// 架构中不存在属性 Attendees 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Attendees
        {
            get
            {
                return this._Attendees;
            }
            set
            {
                this.OnAttendeesChanging(value);
                this.ReportPropertyChanging("Attendees");
                this._Attendees = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Attendees");
                this.OnAttendeesChanged();
            }
        }
        private string _Attendees;
        partial void OnAttendeesChanging(string value);
        partial void OnAttendeesChanged();
        /// <summary>
        /// 架构中不存在属性 AttendeeNames 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AttendeeNames
        {
            get
            {
                return this._AttendeeNames;
            }
            set
            {
                this.OnAttendeeNamesChanging(value);
                this.ReportPropertyChanging("AttendeeNames");
                this._AttendeeNames = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AttendeeNames");
                this.OnAttendeeNamesChanged();
            }
        }
        private string _AttendeeNames;
        partial void OnAttendeeNamesChanging(string value);
        partial void OnAttendeeNamesChanged();
        /// <summary>
        /// 架构中不存在属性 OtherAttendee 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherAttendee
        {
            get
            {
                return this._OtherAttendee;
            }
            set
            {
                this.OnOtherAttendeeChanging(value);
                this.ReportPropertyChanging("OtherAttendee");
                this._OtherAttendee = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("OtherAttendee");
                this.OnOtherAttendeeChanged();
            }
        }
        private string _OtherAttendee;
        partial void OnOtherAttendeeChanging(string value);
        partial void OnOtherAttendeeChanged();
        /// <summary>
        /// 架构中不存在属性 UPAccount 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UPAccount
        {
            get
            {
                return this._UPAccount;
            }
            set
            {
                this.OnUPAccountChanging(value);
                this.ReportPropertyChanging("UPAccount");
                this._UPAccount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UPAccount");
                this.OnUPAccountChanged();
            }
        }
        private string _UPAccount;
        partial void OnUPAccountChanging(string value);
        partial void OnUPAccountChanged();
        /// <summary>
        /// 架构中不存在属性 UPName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UPName
        {
            get
            {
                return this._UPName;
            }
            set
            {
                this.OnUPNameChanging(value);
                this.ReportPropertyChanging("UPName");
                this._UPName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UPName");
                this.OnUPNameChanged();
            }
        }
        private string _UPName;
        partial void OnUPNameChanging(string value);
        partial void OnUPNameChanged();
        /// <summary>
        /// 架构中不存在属性 UPTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime UPTime
        {
            get
            {
                return this._UPTime;
            }
            set
            {
                this.OnUPTimeChanging(value);
                this.ReportPropertyChanging("UPTime");
                this._UPTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UPTime");
                this.OnUPTimeChanged();
            }
        }
        private global::System.DateTime _UPTime;
        partial void OnUPTimeChanging(global::System.DateTime value);
        partial void OnUPTimeChanged();
        /// <summary>
        /// 架构中不存在属性 RecurringRule 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RecurringRule
        {
            get
            {
                return this._RecurringRule;
            }
            set
            {
                this.OnRecurringRuleChanging(value);
                this.ReportPropertyChanging("RecurringRule");
                this._RecurringRule = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RecurringRule");
                this.OnRecurringRuleChanged();
            }
        }
        private string _RecurringRule;
        partial void OnRecurringRuleChanging(string value);
        partial void OnRecurringRuleChanged();
        /// <summary>
        /// 架构中不存在属性 IsAllDayEvent 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllDayEvent
        {
            get
            {
                return this._IsAllDayEvent;
            }
            set
            {
                this.OnIsAllDayEventChanging(value);
                this.ReportPropertyChanging("IsAllDayEvent");
                this._IsAllDayEvent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsAllDayEvent");
                this.OnIsAllDayEventChanged();
            }
        }
        private bool _IsAllDayEvent;
        partial void OnIsAllDayEventChanging(bool value);
        partial void OnIsAllDayEventChanged();
    }
    /// <summary>
    /// 架构中不存在 AzureCalEntities.UserInfo 的注释。
    /// </summary>
    /// <KeyProperties>
    /// UserID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AzureCalEntities", Name="UserInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UserInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 UserInfo 对象。
        /// </summary>
        /// <param name="userID">UserID 的初始值。</param>
        public static UserInfo CreateUserInfo(string userID)
        {
            UserInfo userInfo = new UserInfo();
            userInfo.UserID = userID;
            return userInfo;
        }
        /// <summary>
        /// 架构中不存在属性 UserID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                this.ReportPropertyChanging("UserID");
                this._UserID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserID");
                this.OnUserIDChanged();
            }
        }
        private string _UserID;
        partial void OnUserIDChanging(string value);
        partial void OnUserIDChanged();
        /// <summary>
        /// 架构中不存在属性 NickName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName
        {
            get
            {
                return this._NickName;
            }
            set
            {
                this.OnNickNameChanging(value);
                this.ReportPropertyChanging("NickName");
                this._NickName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NickName");
                this.OnNickNameChanged();
            }
        }
        private string _NickName;
        partial void OnNickNameChanging(string value);
        partial void OnNickNameChanged();
        /// <summary>
        /// 架构中不存在属性 Email 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// 架构中不存在属性 Password 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// 架构中不存在属性 CreateTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return this._CreateTime;
            }
            set
            {
                this.OnCreateTimeChanging(value);
                this.ReportPropertyChanging("CreateTime");
                this._CreateTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateTime");
                this.OnCreateTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
        /// <summary>
        /// 架构中不存在属性 LastLoginTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> LastLoginTime
        {
            get
            {
                return this._LastLoginTime;
            }
            set
            {
                this.OnLastLoginTimeChanging(value);
                this.ReportPropertyChanging("LastLoginTime");
                this._LastLoginTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastLoginTime");
                this.OnLastLoginTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _LastLoginTime;
        partial void OnLastLoginTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastLoginTimeChanged();
    }
}
